### ISSUE TITLE
Filtrar la lista de personas

### ISSUE THREAD

**Issue by migonzalvar** [abertal/alpha#106]
Como usuario quiero buscar una persona a través de una formulario.

**Comment by benitezdemiguel** [comment]
Creado el pull-request de este issue.

**Comment by migonzalvar** [comment]
Podemos mejorar la usabilidad del filtro haciendo que:

- busque no solo en en el campo `name` sino también en `surname`
- encuentra también resultados parciales (`__icontains`)
- opcionalmente, si se está usando PostgreSQL como base de datos, que use https://docs.djangoproject.com/en/1.10/ref/contrib/postgres/lookups/#unaccent

**Comment by benitezdemiguel** [comment]
Están creados los test de los filtros de todos los modelos #128 podemos cerrar este issue o algo más a añadir?

**Comment by migonzalvar** [comment]
Falta usar `unaccent` en PostgreSQL pero lo movemos a otra tarea.
