### ISSUE TITLE
Habilitar paginación en los listados

### ISSUE THREAD

**Issue by migonzalvar** [abertal/alpha#111]
https://docs.djangoproject.com/en/1.10/topics/pagination/

**Comment by ivannieto** [comment]
Asígnamelo, por favor @migonzalvar

**Comment by ivannieto** [comment]
Debo entender que es en todos los listados ¿verdad?

**Comment by migonzalvar** [comment]
Sí. Hay que implmentar una solución genérica para todas las vistas y plantillas que sean listados.

**Comment by migonzalvar** [comment]
@isGroba puedes añádir paginación a los nuevos listados?

**Comment by isGroba** [comment]
Voy a ello
