### ISSUE TITLE
Actualizar a Django 1.11

### ISSUE THREAD

**Issue by migonzalvar** [abertal/alpha#125]

**Comment by benitezdemiguel** [comment]
Nuevo en Django 1.11:

> The LoginView and LogoutView class-based views supersede the deprecated login() and logout() function-based views.

Hay que rehacer el metodo de login, los test y el logout.

> Validators
Added FileExtensionValidator to validate file extensions and validate_image_file_extension to validate image files.

Hay que validar la foto que se sube en Socio

**Comment by isGroba** [comment]
Mergeado en #143
