### ISSUE TITLE
Custodian - emergency_contact

### ISSUE THREAD

**Issue by gvame** [abertal/alpha#127]
Me he dado cuenta, que al crear un registro custodian se crea uno por cada recipient.
Tener el contacto de emergencia dentro del custodian , lleva a tener que rellenar el emergency_contact , para cada uno de los destinatarios.

**Comment by migonzalvar** [comment]
Entiendo. Otra opción es llevar la información de como contactar con el tutor en caso de emergencia al campo de persona. Esto evitaría duplicación de datos. Como contrapartida no se podría tener información de contacto de emergencia diferente por cada destinatario.

**Comment by migonzalvar** [comment]
Cierro la issue. Lo trataremos en otro momento cuando revisemos de nuevo todos los modelos.
