### ISSUE TITLE
Alta destinatario - Error de redireccion

### ISSUE THREAD

**Issue by benitezdemiguel** [abertal/alpha#129]
Cuando desde person-details damos de alta un destinatario se crea pero da error de url o de id de persona

> ValueError at /webapp/person/4/
badly formed hexadecimal UUID string

Aún así se queda registrado como destinatario esa persona por eso supongo que será error de redireccion o de la accion del form.

**Comment by gvame** [comment]
Oído

**Comment by gvame** [comment]
He modificado en una prueba la funcion de retorno, cambiando el id(autoincremental en la tabla recipient) por person_id que es donde se almacena el uuid(de la persona) y parece que está arrglado.

    def get_success_url(self):
        return reverse('person-detail', args=[self.object.person_id])

**Comment by migonzalvar** [comment]
@gvame Si puedes envía una PR sólo con este cambio
