### ISSUE TITLE
Error en firefox javascript:(0);

### ISSUE THREAD

**Issue by migonzalvar** [abertal/alpha#163]
En firefox, al pulsar en un enlace con la referencia hipertextual definida como `href="javascript:(0);`, da error.

Para hacer que ciertos enlaces sean nulos hay que usar otra cosa.

Opciones:

- `"javascript:void(0);"`
- `"javascript:;"`
- `"#"`
- `""`
- ...

**Comment by benitezdemiguel** [comment]
Resuelto en #164
