### ISSUE TITLE
Error paginado cuando no filtro

### ISSUE THREAD

**Issue by migonzalvar** [abertal/alpha#182]
Cuando no hay filtro aplicado, el enlace a la página siguiente no funciona. El enlace contruido es:

```
http://127.0.0.1:8000/webapp/person/?q=None&page=3
```
El valor correcto debería ser `q=&page=3` o incluso omitir `q` por completo.

**Comment by isGroba** [comment]
Arreglado en #185 
igual no es la mejor manera
