### ISSUE TITLE
Cambiar campos estudies por current_course y que sea seleccionable de una lista

### ISSUE THREAD

**Issue by migonzalvar** [abertal/alpha#197]

**Comment by gvame** [comment]
para hacer estos cambios,trabajo sobre mi pr previa?
o como hago para enganchar mis cambios al issue?

**Comment by migonzalvar** [comment]
@gvame Nueva rama, partiendo de master actualizado. En el texto de la *pull request* simplmente pon que `... viene de #197` y el enlace se hace automágicamente.

**Comment by gvame** [comment]
he pensado, que lo más practico seria separar por ciclos educativos como a continuación:

    INFANTILE_COURSES =[
        ('4EI',_('4º Educacion Infantil'))
        ('5EI',_('5º Educacion Infantil'))
        ('6EI',_('6º Educacion Infantil'))
    ]

o hago la clasificacion en un solo grupo, para todos los ciclos?

    INFANTILE_COURSES =[
        ('EI',_('Educacion Infantil'))
        ('EP',_('Educacion Primaria'))
        ('ESO',_('Educación Secundaria Obligatoria'))
        ('BACH',_('Bachillerato'))
        ('MAS',_(Mayores de edad[fp/universitarios...])
    ]

**Comment by migonzalvar** [comment]
Creo que mejor por cursos concretos.

El 25 abr. 2017 6:45 p. m., "gvame" <notifications@github.com> escribió:

he pensado, que lo más practico seria separar por ciclos educativos como a
continuación:

INFANTILE_COURSES =[
    ('4EI',_('4º Educacion Infantil'))
    ('5EI',_('5º Educacion Infantil'))
    ('6EI',_('6º Educacion Infantil'))
]

o hago la clasificacion en un solo grupo, para todos los ciclos?

INFANTILE_COURSES =[
    ('EI',_('Educacion Infantil'))
    ('EP',_('Educacion Primaria'))
    ('ESO',_('Educación Secundaria Obligatoria'))
    ('BACH',_('Bachillerato'))
    ('MAS',_(Mayores de edad[fp/universitarios...])
]

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/abertal/alpha/issues/197#issuecomment-297091520>, or mute
the thread
